project_name: "Real-Time Speech Enhancement"
save_dir: "./checkpoints"

# Dataset
sample_rate: 16000
segement_length: 2.0
frame_size_ms: 20
frame_shift_ms: 10

dataset:
  train_noisy:"./data/noisy/train_noisy"
  train_clean:"./data/clean/train_clean"
  test_noisy:"./data/noisy/test_noisy"
  test_clean:"./data/noisy/train_noisy"

# Model Architecture

encoder:
  out_channels: 256
  kernel_size: 20
  stride: 10

tcn:
  num_block: 8
  channels: 256
  kernel_size: 3
  dilation_base: 2

conformer:
  num_blocks: 2
  d_model: 256
  num_heads: 4
  ff_expansion_factor: 2
  conv_kernel_size: 31
  dropout: 0.1

decoder:
  out_channels: 1

# Training

batch_size: 8
num_epochs: 50
learning_rate: 0.001
optimizer: "adam"
loss_function: "si_snr"
early_stopping_patience: 5
log-interval: 10

metrics:
  - pesq
  - stoi
  - si_snr