sample_rate: 16000
segment_length: 3.0
frame_size_ms: 20
frame_shift_ms: 10

encoder:
  out_channels: 256
  kernel_size: 16         # ↓ Reduced for better time resolution
  stride: 8               # ↓ Smaller stride to preserve more detail

tcn:
  num_blocks: 10          # ↑ Deeper temporal modeling
  channels: 256
  kernel_size: 3
  dilation_base: 2

decoder:
  out_channels: 1

batch_size: 8
num_epochs: 60
learning_rate: 0.0003
optimizer: "adam"
loss_function: "si_snr"   # We'll modify this in code below
early_stopping_patience: 15
log_interval: 10

dataset:
  train_noisy: "/content/real-time-speech-enhancement/data/noisy/train_noisy"
  train_clean: "/content/real-time-speech-enhancement/data/clean/train_clean"
  test_noisy: "/content/real-time-speech-enhancement/data/noisy/test_noisy"
  test_clean: "/content/real-time-speech-enhancement/data/clean/test_clean"

metrics:
  - pesq
  - stoi
  - si_snr